[WIP]データベース 設計
GikaiKamito/chat-space pull request #3
Opened 2019-03-31 07:54 UTC by GikaiKamito

# what
データベース 設計
# why
必要不可欠

2019-03-31 09:09 UTC, ghost requested changes

2019-03-31 09:09 UTC, hiroki5123 commented on README.md
> +|name|string|null:false|
これは不要です！

2019-03-31 09:09 UTC, hiroki5123 commented on README.md
> +- has_many :users,through user_group
アソシエーションが一つ足りないので見直してみましょう

2019-03-31 09:09 UTC, hiroki5123 commented on README.md
> +- has_many :groups,throgh user_group
アソシエーションが一つ足りないので見直してみましょう

2019-03-31 10:35 UTC, GikaiKamito commented on README.md
> +|name|string|null:false|
修正しました

2019-03-31 11:51 UTC, GikaiKamito reviewed
修正しました

2019-03-31 11:51 UTC, GikaiKamito commented on README.md
> +- has_many :groups,throgh user_group
has_many :groups,throgh user_group
のところですか？

2019-04-02 02:49 UTC, GikaiKamito reviewed
修正しました

2019-04-02 03:01 UTC, GikaiKamito commented on README.md
> +- has_many :users,through user_group
修正しました

2019-04-02 03:04 UTC, GikaiKamito reviewed
修正しました

2019-04-02 03:14 UTC, GikaiKamito commented
修正しました

2019-04-02 03:31 UTC, TOMARUMARU commented on README.md
> +|name|string|null:false|
nameは不要です

2019-04-02 03:31 UTC, TOMARUMARU commented on README.md
> +|text|text|null:false|
nullは許容しましょう

2019-04-02 03:31 UTC, TOMARUMARU commented on README.md
> +|user_id|integer|null:false|
不要です

2019-04-02 03:31 UTC, TOMARUMARU commented on README.md
> +|message_id|integer|null:false|
不要です

2019-04-02 04:30 UTC, miyagit commented on README.md
> +-has_many :users_groups
こちらスペース付けて合わせましょう。

2019-04-02 04:30 UTC, miyagit commented on README.md
> +|user_id|integer|null:false|
こちら削除しましょう。

2019-04-04 07:39 UTC, i-date approved these changes
LGTMです^^ マージしましょう！

2019-04-04 08:18 UTC, merged