[WIP]Edit haml_scss
GikaiKamito/chat-space pull request #4
Opened 2019-04-07 03:15 UTC by GikaiKamito

# what
チャットスペースのフロント作成
# why
サービスの中心になるページ

2019-04-07 03:30 UTC, GikaiKamito commented
<img width="1436" alt="スクリーンショット 2019-04-07 12 28 34" src="https://user-images.githubusercontent.com/41457255/55678220-d34f4280-5930-11e9-9517-ae21b825beae.png">

2019-04-07 03:30 UTC, GikaiKamito commented
<img width="1439" alt="スクリーンショット 2019-04-07 12 27 23" src="https://user-images.githubusercontent.com/41457255/55678230-eeba4d80-5930-11e9-9a35-20df127ffd57.png">

2019-04-07 03:32 UTC, hiroki5123 commented
Editボタンのborderと文字の色が違う気がしますので、修正をお願い致します

2019-04-07 03:33 UTC, hiroki5123 commented
また、左上のアイコンの色も違うので修正をお願い致します

2019-04-07 03:35 UTC, ghost requested changes
全体的にインデントが崩れているので、修正をお願い致します。

2019-04-07 03:35 UTC, hiroki5123 commented on Gemfile
> +  gem 'font-awesome-rails'
最後に空行いれてください。

2019-04-07 03:35 UTC, hiroki5123 commented on app/assets/stylesheets/_variable.scss
> +$margin2:0 40px;
最後に空行いれてください。

2019-04-07 03:35 UTC, hiroki5123 commented on app/assets/stylesheets/application.scss
> +	width:100vw;
: のあとは半角スペースを開けてください。
他の部分も修正をお願い致します。

2019-04-07 03:35 UTC, hiroki5123 commented on app/assets/stylesheets/application.scss
> +
ここから下は他のファイルに書いて、application.scssでimportするようにしてください。

2019-04-07 03:35 UTC, hiroki5123 commented on app/views/messages/index.haml
> +        .p2 ttttttt
p2やp3というクラス名はわかりにくいので、group__first-messageとかにしてもらえればいいかと思います。

2019-04-07 03:35 UTC, hiroki5123 commented on app/views/messages/index.haml
> +      .contentleft_head
クラス名はBEMにしたがって命名してください。

2019-04-07 03:35 UTC, hiroki5123 commented on app/views/messages/index.haml
> +  %body
ここから上は削除して大丈夫です。

2019-04-07 08:08 UTC, GikaiKamito commented
<img width="1433" alt="スクリーンショット 2019-04-07 17 07 07" src="https://user-images.githubusercontent.com/41457255/55680676-ab270a00-5957-11e9-8dbe-621f335caa11.png">

2019-04-07 08:10 UTC, GikaiKamito commented on Gemfile
> +  gem 'font-awesome-rails'
修正しました

2019-04-07 08:11 UTC, GikaiKamito commented on app/assets/stylesheets/_variable.scss
> +$margin2:0 40px;
修正しました

2019-04-07 08:11 UTC, GikaiKamito commented on app/assets/stylesheets/application.scss
> +	width:100vw;
修正しました

2019-04-07 08:11 UTC, GikaiKamito commented on app/assets/stylesheets/application.scss
> +
修正しました

2019-04-07 08:11 UTC, GikaiKamito commented on app/views/messages/index.haml
> +        .p2 ttttttt
修正しました

2019-04-07 08:11 UTC, GikaiKamito commented on app/views/messages/index.haml
> +      .contentleft_head
修正しました

2019-04-07 08:23 UTC, GikaiKamito commented on app/views/messages/index.haml
> +  %body
%html
  %body
はエラーになるので削除せず残しました

2019-04-07 08:25 UTC, hiroki5123 commented on app/views/messages/index.haml
> +  %body
エラーになるのはファイル名が間違っているからじゃないですか？
正しいファイル名はindex.html.hamlです。

ここから上は削除して大丈夫ですと書いているのは、すでにapplicatoin.html.hamlで同じ記述をしていて重複するためです。

2019-04-07 08:27 UTC, ghost requested changes

2019-04-07 08:27 UTC, hiroki5123 commented on app/assets/stylesheets/_messages.scss
> +font-weight: bold;
インデントここ崩れています。
また、アンパサンドを使ってください。

2019-04-07 08:27 UTC, hiroki5123 commented on app/assets/stylesheets/_messages.scss
> +    width: calc(100vw - 300px);
インデントずれています。

2019-04-07 08:27 UTC, hiroki5123 commented on app/views/messages/index.haml
> +        .group-third_message tttttttt
なんでfirstとかsecondとかで分けているんですか・・？
CSSを当てたいときに困りませんか？

2019-04-07 09:45 UTC, GikaiKamito commented on app/views/messages/index.haml
> +  %body
修正しました

2019-04-07 09:45 UTC, GikaiKamito commented on app/assets/stylesheets/_messages.scss
> +    width: calc(100vw - 300px);
修正しました

2019-04-07 09:46 UTC, GikaiKamito commented on app/views/messages/index.haml
> +        .group-third_message tttttttt
修正しました

2019-04-07 11:37 UTC, GikaiKamito commented on app/assets/stylesheets/_messages.scss
> +font-weight: bold;
修正しました

2019-04-07 11:55 UTC, yuki-uchida requested changes

2019-04-07 11:55 UTC, yuki-uchida commented on app/assets/stylesheets/_messages.scss
> +.content-right_edit{
BEMに沿ったクラス命名を行い、アンバサンドを活用した省略形で記述しましょう
https://qiita.com/Takuan_Oishii/items/0f0d2c5dc33a9b2d9cb1

2019-04-07 11:55 UTC, yuki-uchida commented on app/views/messages/index.html.haml
> +          %i.fa.fa-image
fa_iconというヘルパーメソッドがあるのでそちらを使いましょう

2019-04-08 01:29 UTC, GikaiKamito commented on app/views/messages/index.html.haml
> +          %i.fa.fa-image
修正しました

2019-04-08 04:20 UTC, GikaiKamito commented on app/assets/stylesheets/_messages.scss
> +.content-right_edit{
修正しました

2019-04-08 04:48 UTC, miyagit commented on app/assets/stylesheets/_content-left.scss
> +		font-weight: bold;
こちらインデントがずれているので修正しましょう。

2019-04-08 04:48 UTC, miyagit commented on app/views/layouts/mailer.html.haml
> +    %meta{:content => "text/html; charset=utf-8", "http-equiv" => "Content-Type"}/
mailer系のファイルは削除してもらって大丈夫です。

2019-04-08 04:48 UTC, miyagit commented on app/views/layouts/application.html.haml
> +    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
ハッシュロケットは修正しましょう。

2019-04-08 05:21 UTC, GikaiKamito commented on app/assets/stylesheets/_content-left.scss
> +		font-weight: bold;
修正しました

2019-04-08 05:22 UTC, GikaiKamito commented on app/views/layouts/mailer.html.haml
> +    %meta{:content => "text/html; charset=utf-8", "http-equiv" => "Content-Type"}/
削除しました

2019-04-08 05:22 UTC, GikaiKamito commented on app/views/layouts/application.html.haml
> +    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
修正しました

2019-04-08 05:38 UTC, kuroko918 approved these changes
いいかと思います！
LGTMです！

2019-04-08 06:14 UTC, merged